name: IINACT build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        dotnet:
          - version: 8.0.x
          - version: 7.0.x
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET ${{ matrix.dotnet.version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet.version }}
    - name: Download Dalamud
      run: |
        curl -Ls -o latest.zip https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
        unzip -q latest.zip -d ${{ env.DALAMUD_HOME }}
    - name: Build with .NET ${{ matrix.dotnet.version }}
      run: dotnet build -c Release
    - name: Prepare Build Artifact
      run: unzip IINACT/bin/Release/win-x64/IINACT/latest.zip -d Artifact
    - name: Upload IINACT
      uses: actions/upload-artifact@v4
      with:
        name: IINACT_dotnet${{ matrix.dotnet.version }}
        path: |
          Artifact/*
          !Artifact/**/*.pdb