name: IINACT build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        dotnet:
          - version: 8.0.x
          - version: 7.0.x
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET ${{ matrix.dotnet.version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet.version }}
    - name: Download Dalamud
      run: curl -L -o - https://goatcorp.github.io/dalamud-distrib/stg/latest.zip | unzip - -d /tmp/dalamud
    - name: Build with .NET ${{ matrix.dotnet.version }}
      run: dotnet build -c release
    - name: Prepare Build Artifact
      run: cp IINACT/bin/Release/win-x64/IINACT/latest.zip IINACT_${{ matrix.dotnet.version }}.zip
    - name: Upload IINACT
      uses: actions/upload-artifact@v4
      with:
        path: IINACT_${{ matrix.dotnet.version }}.zip